### ISSUE TITLE
effechecka down?

### ISSUE THREAD

**Issue by diatomsRcool** [jhpoelen/effechecka#75] opened 2017-11-01 14:22 UTC
I've been getting "bad request" on the same queries for two days. It usually only takes one to complete a query. Is something wrong?

**Comment by jhammock** [comment] 2017-11-01 14:35
There has been a lot of activity on the server lately. I just shut down everything for users who haven't logged in for a couple of days. That may have freed up enough to get effechecka moving. (But possibly not. I cannot see capacity allocations, just identities.)

**Comment by jhpoelen** [comment] 2017-11-01 14:54
please provide the query.

**Comment by jhpoelen** [comment] 2017-11-01 14:55
An increased load on the server should not generate "bad requests", but I'd like to reproduce your issue to we can get to the bottom of it.

**Comment by jhpoelen** [comment] 2017-11-01 14:57
Also, for future issues, please provide as much detail as possible, so that it is easier to get to the root of it. Thanks for being patient.

**Comment by diatomsRcool** [comment] 2017-11-01 14:59
Here's the query
http://api.effechecka.org/checklist.tsv?traitSelector=&wktString=GEOMETRYCOLLECTION%28POLYGON%20%28%28-13.709%2012.676%2C%20-12.888%2012.541%2C%20-12.45%2012.392%2C%20-11.46%2012.441%2C%20-11.312%2012.021%2C%20-10.79%2012.109%2C%20-10.516%2012.113%2C%20-9.883%2012.057%2C%20-9.34%2012.243%2C%20-9.162%2012.486%2C%20-8.897%2012.152%2C%20-8.692%2011.636%2C%20-8.376%2011.367%2C%20-8.479%2011.289%2C%20-8.515%2010.972%2C%20-8.276%2010.853%2C%20-8.12%2010.422%2C%20-8.017%2010.097%2C%20-8.101%209.833%2C%20-7.92%209.187%2C%20-7.961%208.81%2C%20-7.745%208.373%2C%20-7.938%208.501%2C%20-8.069%208.162%2C%20-7.948%208.007%2C%20-8.071%207.79%2C%20-8.565%207.626%2C%20-8.709%207.508%2C%20-9.104%207.194%2C%20-9.357%207.612%2C%20-9.52%208.179%2C%20-9.628%208.459%2C%20-10.055%208.421%2C%20-10.386%208.493%2C%20-10.622%208.542%2C%20-10.733%209.084%2C%20-10.827%209.518%2C%20-11.886%209.997%2C%20-12.432%209.882%2C%20-12.687%209.409%2C%20-12.992%209.113%2C%20-13.25%209.16%2C%20-13.413%209.279%2C%20-13.554%209.5%2C%20-13.663%209.83%2C%20-13.684%209.938%2C%20-14.032%2010.104%2C%20-14.138%2010.047%2C%20-14.456%2010.208%2C%20-14.667%2010.475%2C%20-14.723%2010.699%2C%20-14.754%2010.836%2C%20-14.659%2011.03%2C%20-14.665%2011.507%2C%20-14.089%2011.631%2C%20-13.713%2011.71%2C%20-13.857%2012.244%2C%20-13.637%2012.45%2C%20-13.709%2012.676%29%29%29

**Comment by diatomsRcool** [comment] 2017-11-01 15:00
I've found that on the same query, the first time I'll get processing and then I'll get bad request until its ready.

**Comment by jhpoelen** [comment] 2017-11-01 15:23
Thanks for sharing. Looks like @gauravyeole has launched a three pyspark-shell four days ago (92 hours ago) that allocate a significant portion of the cluster. This is causing your requests (submitted three days ago) to be starved for resources: three checklist requests are now continually checking whether there are enough resources to calculate a checklist.

I'll have a look whether we can tweak the parameters a bit so that checklist calculations resolve fewer resource to be run. Another example we need features documented in https://github.com/bio-guoda/guoda-services/issues/19 https://github.com/bio-guoda/guoda-services/issues/9  https://github.com/bio-guoda/guoda-services/issues/28 .

**Comment by jhpoelen** [comment] 2017-11-01 16:54
@diatomsRcool I've change the status message in case the cluster is overloaded or unavailable - instead of returning BadRequest (400), now Service Unavailable (503) is returned. Please let me know if this helps with troubleshooting your scripts.

I've included a screenshot of what I see in my browser when using [your query](http://api.effechecka.org/checklist.tsv?traitSelector=&wktString=GEOMETRYCOLLECTION%28POLYGON%20%28%28-13.709%2012.676%2C%20-12.888%2012.541%2C%20-12.45%2012.392%2C%20-11.46%2012.441%2C%20-11.312%2012.021%2C%20-10.79%2012.109%2C%20-10.516%2012.113%2C%20-9.883%2012.057%2C%20-9.34%2012.243%2C%20-9.162%2012.486%2C%20-8.897%2012.152%2C%20-8.692%2011.636%2C%20-8.376%2011.367%2C%20-8.479%2011.289%2C%20-8.515%2010.972%2C%20-8.276%2010.853%2C%20-8.12%2010.422%2C%20-8.017%2010.097%2C%20-8.101%209.833%2C%20-7.92%209.187%2C%20-7.961%208.81%2C%20-7.745%208.373%2C%20-7.938%208.501%2C%20-8.069%208.162%2C%20-7.948%208.007%2C%20-8.071%207.79%2C%20-8.565%207.626%2C%20-8.709%207.508%2C%20-9.104%207.194%2C%20-9.357%207.612%2C%20-9.52%208.179%2C%20-9.628%208.459%2C%20-10.055%208.421%2C%20-10.386%208.493%2C%20-10.622%208.542%2C%20-10.733%209.084%2C%20-10.827%209.518%2C%20-11.886%209.997%2C%20-12.432%209.882%2C%20-12.687%209.409%2C%20-12.992%209.113%2C%20-13.25%209.16%2C%20-13.413%209.279%2C%20-13.554%209.5%2C%20-13.663%209.83%2C%20-13.684%209.938%2C%20-14.032%2010.104%2C%20-14.138%2010.047%2C%20-14.456%2010.208%2C%20-14.667%2010.475%2C%20-14.723%2010.699%2C%20-14.754%2010.836%2C%20-14.659%2011.03%2C%20-14.665%2011.507%2C%20-14.089%2011.631%2C%20-13.713%2011.71%2C%20-13.857%2012.244%2C%20-13.637%2012.45%2C%20-13.709%2012.676%29%29%29) - 

![screenshot from 2017-11-01 09-53-02](https://user-images.githubusercontent.com/1084872/32286403-9760339c-beea-11e7-9165-07a8ca6c6656.png)

**Comment by jhpoelen** [comment] 2017-11-01 16:57
Please note that if you'd like to check for the status of the checklist, you might want to consider using the ```/checklist?...``` endpoint. For your checklist query, this would be something like [this checklist summart](http://api.effechecka.org/checklist?traitSelector=&wktString=GEOMETRYCOLLECTION%28POLYGON%20%28%28-13.709%2012.676%2C%20-12.888%2012.541%2C%20-12.45%2012.392%2C%20-11.46%2012.441%2C%20-11.312%2012.021%2C%20-10.79%2012.109%2C%20-10.516%2012.113%2C%20-9.883%2012.057%2C%20-9.34%2012.243%2C%20-9.162%2012.486%2C%20-8.897%2012.152%2C%20-8.692%2011.636%2C%20-8.376%2011.367%2C%20-8.479%2011.289%2C%20-8.515%2010.972%2C%20-8.276%2010.853%2C%20-8.12%2010.422%2C%20-8.017%2010.097%2C%20-8.101%209.833%2C%20-7.92%209.187%2C%20-7.961%208.81%2C%20-7.745%208.373%2C%20-7.938%208.501%2C%20-8.069%208.162%2C%20-7.948%208.007%2C%20-8.071%207.79%2C%20-8.565%207.626%2C%20-8.709%207.508%2C%20-9.104%207.194%2C%20-9.357%207.612%2C%20-9.52%208.179%2C%20-9.628%208.459%2C%20-10.055%208.421%2C%20-10.386%208.493%2C%20-10.622%208.542%2C%20-10.733%209.084%2C%20-10.827%209.518%2C%20-11.886%209.997%2C%20-12.432%209.882%2C%20-12.687%209.409%2C%20-12.992%209.113%2C%20-13.25%209.16%2C%20-13.413%209.279%2C%20-13.554%209.5%2C%20-13.663%209.83%2C%20-13.684%209.938%2C%20-14.032%2010.104%2C%20-14.138%2010.047%2C%20-14.456%2010.208%2C%20-14.667%2010.475%2C%20-14.723%2010.699%2C%20-14.754%2010.836%2C%20-14.659%2011.03%2C%20-14.665%2011.507%2C%20-14.089%2011.631%2C%20-13.713%2011.71%2C%20-13.857%2012.244%2C%20-13.637%2012.45%2C%20-13.709%2012.676%29%29%29)

In my browser, this returns:

```json
{"selector":{"uuid":"30ad9dd5-2708-5189-9835-a7dcfbcf1369","taxonSelector":"","wktString":"GEOMETRYCOLLECTION(POLYGON ((-13.709 12.676, -12.888 12.541, -12.45 12.392, -11.46 12.441, -11.312 12.021, -10.79 12.109, -10.516 12.113, -9.883 12.057, -9.34 12.243, -9.162 12.486, -8.897 12.152, -8.692 11.636, -8.376 11.367, -8.479 11.289, -8.515 10.972, -8.276 10.853, -8.12 10.422, -8.017 10.097, -8.101 9.833, -7.92 9.187, -7.961 8.81, -7.745 8.373, -7.938 8.501, -8.069 8.162, -7.948 8.007, -8.071 7.79, -8.565 7.626, -8.709 7.508, -9.104 7.194, -9.357 7.612, -9.52 8.179, -9.628 8.459, -10.055 8.421, -10.386 8.493, -10.622 8.542, -10.733 9.084, -10.827 9.518, -11.886 9.997, -12.432 9.882, -12.687 9.409, -12.992 9.113, -13.25 9.16, -13.413 9.279, -13.554 9.5, -13.663 9.83, -13.684 9.938, -14.032 10.104, -14.138 10.047, -14.456 10.208, -14.667 10.475, -14.723 10.699, -14.754 10.836, -14.659 11.03, -14.665 11.507, -14.089 11.631, -13.713 11.71, -13.857 12.244, -13.637 12.45, -13.709 12.676)))","traitSelector":""},"status":"busy","items":[]}```

**Comment by jhammock** [comment] 2017-11-01 17:04
Point of Information: Service Unavailable is distinct from Busy?

**Comment by jhpoelen** [comment] 2017-11-01 17:37
Definition of Service Unavailable (from https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#503)

```The server is currently unavailable (because it is overloaded or down for maintenance). Generally, this is a temporary state.```

This was the http status code closest to our own "busy" which pretty much indicates that no data is available for the request and the client should check back later.

Does that help?

**Comment by jhammock** [comment] 2017-11-01 19:12
OK, so the meaning of the two terms is the same, but perhaps the context is different? I think "busy" still appears for an API call to Effechecka or Fresh Data?

**Comment by jhpoelen** [comment] 2017-11-01 20:32
Yep, the context of the 503 code is http return codes, whereas "busy" is an custom status code used for effechecka/freshdata result summaries.

**Comment by jhpoelen** [comment] 2017-11-01 22:21
Looks like the data is available now from the reported query is available now. See [checklist.tsv](http://api.effechecka.org/checklist.tsv?traitSelector=&wktString=GEOMETRYCOLLECTION%28POLYGON%20%28%28-13.709%2012.676%2C%20-12.888%2012.541%2C%20-12.45%2012.392%2C%20-11.46%2012.441%2C%20-11.312%2012.021%2C%20-10.79%2012.109%2C%20-10.516%2012.113%2C%20-9.883%2012.057%2C%20-9.34%2012.243%2C%20-9.162%2012.486%2C%20-8.897%2012.152%2C%20-8.692%2011.636%2C%20-8.376%2011.367%2C%20-8.479%2011.289%2C%20-8.515%2010.972%2C%20-8.276%2010.853%2C%20-8.12%2010.422%2C%20-8.017%2010.097%2C%20-8.101%209.833%2C%20-7.92%209.187%2C%20-7.961%208.81%2C%20-7.745%208.373%2C%20-7.938%208.501%2C%20-8.069%208.162%2C%20-7.948%208.007%2C%20-8.071%207.79%2C%20-8.565%207.626%2C%20-8.709%207.508%2C%20-9.104%207.194%2C%20-9.357%207.612%2C%20-9.52%208.179%2C%20-9.628%208.459%2C%20-10.055%208.421%2C%20-10.386%208.493%2C%20-10.622%208.542%2C%20-10.733%209.084%2C%20-10.827%209.518%2C%20-11.886%209.997%2C%20-12.432%209.882%2C%20-12.687%209.409%2C%20-12.992%209.113%2C%20-13.25%209.16%2C%20-13.413%209.279%2C%20-13.554%209.5%2C%20-13.663%209.83%2C%20-13.684%209.938%2C%20-14.032%2010.104%2C%20-14.138%2010.047%2C%20-14.456%2010.208%2C%20-14.667%2010.475%2C%20-14.723%2010.699%2C%20-14.754%2010.836%2C%20-14.659%2011.03%2C%20-14.665%2011.507%2C%20-14.089%2011.631%2C%20-13.713%2011.71%2C%20-13.857%2012.244%2C%20-13.637%2012.45%2C%20-13.709%2012.676%29%29%29) or [checklist.zip](https://github.com/jhpoelen/effechecka/files/1435882/checklist.zip)

So, root cause - resource constraints on the spark cluster and confusing status reporting. 

@mjcollin @godfoder perhaps something to discuss for next meeting - how to reserve resources so that effechecka/freshdata can always do a little crunching while spark shells are idling (or are busy) in the background.

**Comment by mjcollin** [comment] 2017-11-02 11:58
I stopped some notebooks so there are resources again.

Yes, we need to figure out better scheduling or reservations.

**Comment by jhpoelen** [comment] 2017-11-02 13:31
@diatomsRcool if you feel this issue has been resolved, please close it. Otherwise, please elaborate on what you think needs to be done to address your needs.

**Closed** 2017-11-02 13:45 UTC
