### ISSUE TITLE
Surprisingly few requested records saved to EOL

### ISSUE THREAD

**Issue by jhammock** [jhpoelen/effechecka#34] opened 2015-10-26 21:35 UTC
This query:

http://www.effechecka.org/#geometry=POLYGON%28%28-60.99609375%2018.93746442964186%2C-60.99609375%2010.444597722834875%2C-69.78515625%2010.444597722834875%2C-69.78515625%2018.93746442964186%2C-60.99609375%2018.93746442964186%29%29&hasSpatialIssue=false&height=200&lat=14.732386081418454&limit=20&lng=-65.390625&scientificName=Actinopterygii&taxonSelector=Actinopterygii&traitSelector=&width=200&wktString=ENVELOPE%28-69.78515625%2C-60.99609375%2C18.93746442964186%2C10.444597722834875%29&zoom=5

retrieved 1728 taxa. Requested 1200 save to collection. 

http://eol.org/collections/119689 received 59 taxa. They're bony fishes, so names on EOL should be pretty good. Is there any way to examine how the name matching went? If it's a GlobalNames barrier, that's a bummer...

**Comment by jhpoelen** [comment] 2015-10-26 22:26
Easy check is to download the eol_page_ids.csv and inspect number of unique page ids. As far as I can tell, way more than 59 taxa have resolved to an eol page id.

I was unable to reproduce the issue . . . my attempt to save up to 1200 taxa to eol collection resulted in an error message and no collection is created. 

Could you please send me the content of your eol_page_ids.csv file?

**Comment by jhpoelen** [comment] 2015-10-26 22:38
Note that a related (and open) idigbio issue #6 results in (species) names such as ```Labridae Thalassoma bifasciatum```, an apparent concatenation of ```Labridae``` and ```Thalassoma bifasciatum```. The species appears twice in the query above: the correct name is also available ```Thalassoma bifasciatum``` although fewer occurrences were reported using that name (1) than the family - species name (80).

@godfoder @mjcollin are you aware of this iDigBio naming issue?

**Comment by jhammock** [comment] 2015-10-27 15:14
Un-truncated results in csv export:

https://dl.dropboxusercontent.com/u/33761226/checklist%20%284%29.csv

**Comment by jhammock** [comment] 2015-10-27 15:19
EOL page IDs:

https://dl.dropboxusercontent.com/u/33761226/eolpageids.csv

whoa, lots of duplicates, but ata a glance, not enough to explain this.

**Comment by jhpoelen** [comment] 2015-10-28 15:01
@jhammock I was not able to reproduce your ability to create an eol collection containing 59 items from an expected list of about 1200 items. However, I did see a collection appear that contained 402 items after attempting to reproduce the issue: http://eol.org/collections/119690 . Note that the collection seems to be corrupt (cannot view the actual list, see attached screenshot) and cannot be deleted. Also note that when the collection was created, an error message was generated. 

Also, duplicate ids should no longer appear in eol page id csv download.

Closing issue, because it is a result of bug in the EOL write API that is documented here: https://github.com/EOL/tramea/issues/35 .

**Closed by jhpoelen** 2015-10-28 15:01 UTC
