### ISSUE TITLE
query is taking longer than expected

### ISSUE THREAD

**Issue by jhammock** [jhpoelen/effechecka#48] opened 2016-09-08 13:51 UTC
There are many points to this polygon; I don't know enough to tell whether that's the cause of the delay. If this is expected behaviour, no worries. It's been 15 or 20 hours since I made the query, so I'm reporting just in case it's stuck:

http://www.effechecka.org/?limit=20&taxonSelector=Eukaryota&traitSelector=&wktString=POLYGON%20%28%28-157.83679962158203%2021.5305156590244%2C%20-157.72693634033203%2021.457681868047725%2C%20-157.7437591552734%2021.452569356479923%2C%20-157.7750015258789%2021.459599013661023%2C%20-157.77706146240234%2021.445219807040345%2C%20-157.7695083618164%2021.445219807040345%2C%20-157.73826599121094%2021.433076261847244%2C%20-157.74478912353516%2021.427643296045733%2C%20-157.7633285522461%2021.42636492176607%2C%20-157.76813507080078%2021.41390018602608%2C%20-157.781867980957%2021.41006466872806%2C%20-157.80590057373047%2021.427962887866645%2C%20-157.8179168701172%2021.450652118422532%2C%20-157.84469604492188%2021.45800139406767%2C%20-157.8464126586914%2021.4730183267972%2C%20-157.84366607666013%2021.482602793633436%2C%20-157.85362243652344%2021.487394790459224%2C%20-157.8573989868164%2021.514546458282457%2C%20-157.84229278564453%2021.517421043946072%2C%20-157.83679962158203%2021.5305156590244%29%29

**Comment by jhpoelen** [comment] 2016-09-08 20:01
The query results are now available . . . no records ( see screenshot below ). Perhaps the source do not mention Eukaryota as a taxon name? Please let me know if this (empty) result is unexpected.

Root cause was a spam event (see #50) and a resource allocation issue (see #49). Closing this issue.

![screen shot 2016-09-08 at 12 59 30 pm](https://cloud.githubusercontent.com/assets/1084872/18364699/25e5f50a-75c4-11e6-873c-953b60e01869.png)

**Closed by jhpoelen** 2016-09-08 20:01 UTC
