### ISSUE TITLE
data for /effechecka-master/

### ISSUE THREAD

**Issue by eliagbayani** [jhpoelen/effechecka#52] opened 2016-11-21 08:06 UTC
Hi @jhpoelen,
Setting up on my local.
Using the /effechecka-master/ from: https://github.com/jhpoelen/effechecka/archive/master.zip
to launch the effechecka-api is unhealthy on my marathon. I guess because I don’t have the /data/ needed to serve request such as:

/checklist?limit=20&taxonSelector=Aves%2CInsecta&traitSelector=&wktString=ENVELOPE(-72.147216796875%2C-69.949951171875%2C43.11702412135048%2C41.49212083968776)&
or
/occurrences?limit=5&taxonSelector=Aves%2CInsecta&wktString=POLYGON%20((-72.147216796875%2041.492120839687786%2C%20-72.147216796875%2043.11702412135048%2C%20-69.949951171875%2043.11702412135048%2C%20-69.949951171875%2041.492120839687786%2C%20-72.147216796875%2041.492120839687786))

My question is: what file(s) should I copy from int@c18node15/data/ so my local effechecka-api can serve such /checklist? or /occurrences? type of requests.

Thanks.

**Comment by jhammock** [comment] 2016-11-21 13:36
Gosh; do you mean the actual occurrence data? It may be a thankless task to try to get queries running from the whole dataset on your local machine, Eli. (You might use a sample, I suppose.) They will, I imagine, be very slow, which might make testing painful. In my ignorance, I wonder if this is a good point to try migrating components to the Spark cluster? (@mjcollin or @godfoder may be able to comment on access and timing.)

**Comment by eliagbayani** [comment] 2016-11-21 13:41
Yes, certainly not the entire dataset. I was thinking of a minimum dataset (yes just a sample) just to check if the local setup actually works. That is, was able to query and show results.

**Comment by jhpoelen** [comment] 2016-11-21 16:04
Now that you have all systems running, you should be able to import a smallish dataset (reefsurvey) and do your local calculations on that. Could you attach the log files that indicate the root cause of the web api poor health?

**Comment by eliagbayani** [comment] 2016-11-22 03:27
These are the error and output logs from Marathon UI for unhealthy effechecka-api:
[error logs.txt](https://github.com/jhpoelen/effechecka/files/605358/error.logs.txt)
[output logs.txt](https://github.com/jhpoelen/effechecka/files/605357/output.logs.txt)

**Comment by jhpoelen** [comment] 2016-12-19 16:38
@eliagbayani please let me know if your questions have been answered. If so, please close the issue.

**Closed** 2017-01-18 00:45 UTC

**Comment by eliagbayani** [comment] 2017-01-18 12:33
Thanks @jhpoelen. Sorry fell into the cracks.
