### ISSUE TITLE
server problem?

### ISSUE THREAD

**Issue by diatomsRcool** [jhpoelen/effechecka#80] opened 2017-12-05 21:04 UTC
I'm getting lots of messages
"The server is currently unavailable (because it is overloaded or down for maintenance)."
when making checklists. Is there a problem with the server?

**Comment by jhammock** [comment] 2017-12-05 21:15
The cluster wasn't very active, according to jupyter. I stopped a couple of servers, leaving just one active. I'm not running anything myself.

**Comment by jhammock** [comment] 2017-12-05 21:16
oops, this should probably be reported in https://github.com/bio-guoda/guoda-services/issues if that didn't happen to get you unstuck.

**Comment by jhpoelen** [comment] 2017-12-06 01:15
duplicate of https://github.com/bio-guoda/guoda-services/issues/39 . Closing issue.

**Closed by jhpoelen** 2017-12-06 01:15 UTC
